/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SidebarRouteImport } from './routes/sidebar'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as ArtifactRouteImport } from './routes/artifact'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ArtifactsIndexRouteImport } from './routes/artifacts.index'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SidebarThreadIdRouteImport } from './routes/sidebar.$threadId'
import { Route as SettingsThreadsRouteImport } from './routes/settings.threads'
import { Route as SettingsOrchestrationRouteImport } from './routes/settings.orchestration'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as ChangesThreadIdRouteImport } from './routes/changes.$threadId'
import { Route as ArtifactsTargetIdRouteImport } from './routes/artifacts.$targetId'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ArtifactsTargetIdIndexRouteImport } from './routes/artifacts.$targetId.index'
import { Route as ArtifactsTargetIdArtifactTitleRouteImport } from './routes/artifacts.$targetId.$artifactTitle'

const SidebarRoute = SidebarRouteImport.update({
  id: '/sidebar',
  path: '/sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactRoute = ArtifactRouteImport.update({
  id: '/artifact',
  path: '/artifact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsIndexRoute = ArtifactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtifactsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SidebarThreadIdRoute = SidebarThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => SidebarRoute,
} as any)
const SettingsThreadsRoute = SettingsThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOrchestrationRoute = SettingsOrchestrationRouteImport.update({
  id: '/orchestration',
  path: '/orchestration',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const ChangesThreadIdRoute = ChangesThreadIdRouteImport.update({
  id: '/changes/$threadId',
  path: '/changes/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsTargetIdRoute = ArtifactsTargetIdRouteImport.update({
  id: '/$targetId',
  path: '/$targetId',
  getParentRoute: () => ArtifactsRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ArtifactsTargetIdIndexRoute = ArtifactsTargetIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtifactsTargetIdRoute,
} as any)
const ArtifactsTargetIdArtifactTitleRoute =
  ArtifactsTargetIdArtifactTitleRouteImport.update({
    id: '/$artifactTitle',
    path: '/$artifactTitle',
    getParentRoute: () => ArtifactsTargetIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/artifact': typeof ArtifactRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/sidebar': typeof SidebarRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/artifacts/$targetId': typeof ArtifactsTargetIdRouteWithChildren
  '/changes/$threadId': typeof ChangesThreadIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/orchestration': typeof SettingsOrchestrationRoute
  '/settings/threads': typeof SettingsThreadsRoute
  '/sidebar/$threadId': typeof SidebarThreadIdRoute
  '/artifacts/': typeof ArtifactsIndexRoute
  '/artifacts/$targetId/$artifactTitle': typeof ArtifactsTargetIdArtifactTitleRoute
  '/artifacts/$targetId/': typeof ArtifactsTargetIdIndexRoute
}
export interface FileRoutesByTo {
  '/artifact': typeof ArtifactRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sidebar': typeof SidebarRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/changes/$threadId': typeof ChangesThreadIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/orchestration': typeof SettingsOrchestrationRoute
  '/settings/threads': typeof SettingsThreadsRoute
  '/sidebar/$threadId': typeof SidebarThreadIdRoute
  '/': typeof ChatIndexRoute
  '/artifacts': typeof ArtifactsIndexRoute
  '/artifacts/$targetId/$artifactTitle': typeof ArtifactsTargetIdArtifactTitleRoute
  '/artifacts/$targetId': typeof ArtifactsTargetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/artifact': typeof ArtifactRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/sidebar': typeof SidebarRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/artifacts/$targetId': typeof ArtifactsTargetIdRouteWithChildren
  '/changes/$threadId': typeof ChangesThreadIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/orchestration': typeof SettingsOrchestrationRoute
  '/settings/threads': typeof SettingsThreadsRoute
  '/sidebar/$threadId': typeof SidebarThreadIdRoute
  '/_chat/': typeof ChatIndexRoute
  '/artifacts/': typeof ArtifactsIndexRoute
  '/artifacts/$targetId/$artifactTitle': typeof ArtifactsTargetIdArtifactTitleRoute
  '/artifacts/$targetId/': typeof ArtifactsTargetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifact'
    | '/artifacts'
    | '/settings'
    | '/sidebar'
    | '/$threadId'
    | '/artifacts/$targetId'
    | '/changes/$threadId'
    | '/settings/archived'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/orchestration'
    | '/settings/threads'
    | '/sidebar/$threadId'
    | '/artifacts/'
    | '/artifacts/$targetId/$artifactTitle'
    | '/artifacts/$targetId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/artifact'
    | '/settings'
    | '/sidebar'
    | '/$threadId'
    | '/changes/$threadId'
    | '/settings/archived'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/orchestration'
    | '/settings/threads'
    | '/sidebar/$threadId'
    | '/'
    | '/artifacts'
    | '/artifacts/$targetId/$artifactTitle'
    | '/artifacts/$targetId'
  id:
    | '__root__'
    | '/_chat'
    | '/artifact'
    | '/artifacts'
    | '/settings'
    | '/sidebar'
    | '/_chat/$threadId'
    | '/artifacts/$targetId'
    | '/changes/$threadId'
    | '/settings/archived'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/orchestration'
    | '/settings/threads'
    | '/sidebar/$threadId'
    | '/_chat/'
    | '/artifacts/'
    | '/artifacts/$targetId/$artifactTitle'
    | '/artifacts/$targetId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  ArtifactRoute: typeof ArtifactRoute
  ArtifactsRoute: typeof ArtifactsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  SidebarRoute: typeof SidebarRouteWithChildren
  ChangesThreadIdRoute: typeof ChangesThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sidebar': {
      id: '/sidebar'
      path: '/sidebar'
      fullPath: '/sidebar'
      preLoaderRoute: typeof SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifact': {
      id: '/artifact'
      path: '/artifact'
      fullPath: '/artifact'
      preLoaderRoute: typeof ArtifactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/': {
      id: '/artifacts/'
      path: '/'
      fullPath: '/artifacts/'
      preLoaderRoute: typeof ArtifactsIndexRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/sidebar/$threadId': {
      id: '/sidebar/$threadId'
      path: '/$threadId'
      fullPath: '/sidebar/$threadId'
      preLoaderRoute: typeof SidebarThreadIdRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/settings/threads': {
      id: '/settings/threads'
      path: '/threads'
      fullPath: '/settings/threads'
      preLoaderRoute: typeof SettingsThreadsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/orchestration': {
      id: '/settings/orchestration'
      path: '/orchestration'
      fullPath: '/settings/orchestration'
      preLoaderRoute: typeof SettingsOrchestrationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/changes/$threadId': {
      id: '/changes/$threadId'
      path: '/changes/$threadId'
      fullPath: '/changes/$threadId'
      preLoaderRoute: typeof ChangesThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/$targetId': {
      id: '/artifacts/$targetId'
      path: '/$targetId'
      fullPath: '/artifacts/$targetId'
      preLoaderRoute: typeof ArtifactsTargetIdRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/artifacts/$targetId/': {
      id: '/artifacts/$targetId/'
      path: '/'
      fullPath: '/artifacts/$targetId/'
      preLoaderRoute: typeof ArtifactsTargetIdIndexRouteImport
      parentRoute: typeof ArtifactsTargetIdRoute
    }
    '/artifacts/$targetId/$artifactTitle': {
      id: '/artifacts/$targetId/$artifactTitle'
      path: '/$artifactTitle'
      fullPath: '/artifacts/$targetId/$artifactTitle'
      preLoaderRoute: typeof ArtifactsTargetIdArtifactTitleRouteImport
      parentRoute: typeof ArtifactsTargetIdRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface ArtifactsTargetIdRouteChildren {
  ArtifactsTargetIdArtifactTitleRoute: typeof ArtifactsTargetIdArtifactTitleRoute
  ArtifactsTargetIdIndexRoute: typeof ArtifactsTargetIdIndexRoute
}

const ArtifactsTargetIdRouteChildren: ArtifactsTargetIdRouteChildren = {
  ArtifactsTargetIdArtifactTitleRoute: ArtifactsTargetIdArtifactTitleRoute,
  ArtifactsTargetIdIndexRoute: ArtifactsTargetIdIndexRoute,
}

const ArtifactsTargetIdRouteWithChildren =
  ArtifactsTargetIdRoute._addFileChildren(ArtifactsTargetIdRouteChildren)

interface ArtifactsRouteChildren {
  ArtifactsTargetIdRoute: typeof ArtifactsTargetIdRouteWithChildren
  ArtifactsIndexRoute: typeof ArtifactsIndexRoute
}

const ArtifactsRouteChildren: ArtifactsRouteChildren = {
  ArtifactsTargetIdRoute: ArtifactsTargetIdRouteWithChildren,
  ArtifactsIndexRoute: ArtifactsIndexRoute,
}

const ArtifactsRouteWithChildren = ArtifactsRoute._addFileChildren(
  ArtifactsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsOrchestrationRoute: typeof SettingsOrchestrationRoute
  SettingsThreadsRoute: typeof SettingsThreadsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsOrchestrationRoute: SettingsOrchestrationRoute,
  SettingsThreadsRoute: SettingsThreadsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface SidebarRouteChildren {
  SidebarThreadIdRoute: typeof SidebarThreadIdRoute
}

const SidebarRouteChildren: SidebarRouteChildren = {
  SidebarThreadIdRoute: SidebarThreadIdRoute,
}

const SidebarRouteWithChildren =
  SidebarRoute._addFileChildren(SidebarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  ArtifactRoute: ArtifactRoute,
  ArtifactsRoute: ArtifactsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  SidebarRoute: SidebarRouteWithChildren,
  ChangesThreadIdRoute: ChangesThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
